services:
  news_app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: chmnu_news_backend:latest
    container_name: news_app
    ports:
      - "${DJANGO_PORT}:8000"
    command: "sh /entrypoint.sh"
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - static:/app/static/
      - ..:/app/
    restart: unless-stopped

volumes:
  static: