services:
  postgres:
    image: postgres:latest
    container_name: news_db
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER} -d ${POSTGRES_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - postgres
    links:
      - postgres:postgres
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - ../.env
    restart: always

volumes:
  postgres_data:
  pgadmin-data: