# Generated by Django 5.2 on 2025-04-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="User's Score"),
        ),
    ]
