name: Test Application on Push
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Copy env file
        run: cp .env_example .env
      - name: Build docker image
        run: make app
      - name: Test Application
        run: make test-run-test
